### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by dprov** [Siidej/OmniMVS_Binocular#1]
Hi, 
I would like to know under what license you would like to publish this code, to know if/how it can be used. 

Thanks!

**Comment by Siidej** [comment]
> Hi, I would like to know under what license you would like to publish this code, to know if/how it can be used.
> 
> Thanks!

Hi, 
Since it's a modification of @[matsuren](https://github.com/matsuren) 's repo, I think this version should follow his license.

**Comment by dprov** [comment]
Great, thanks!
